"""Add favorite tracks and listening history

Revision ID: 78c9ebc1d647
Revises: a39296e22de0
Create Date: 2025-12-01 09:47:21.047445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c9ebc1d647'
down_revision = 'a39296e22de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=100), nullable=False),
    sa.Column('track_name', sa.String(length=200), nullable=True),
    sa.Column('artist_name', sa.String(length=200), nullable=True),
    sa.Column('album_name', sa.String(length=200), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spotify_track_id', name='unique_user_track')
    )
    op.create_table('listening_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=100), nullable=False),
    sa.Column('track_name', sa.String(length=200), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listening_history')
    op.drop_table('favorite_track')
    # ### end Alembic commands ###
